### ISSUE TITLE
mac下,qt-browser分支登录时候报错.

### ISSUE THREAD

**Issue by AdamChrist** [CaoZ/JD-Coin#20]
系统 : mac os 10.12.6
python : 3.6.2
ps : python 是使用 pyenv安装的.
在打开浏览器窗口的一瞬间就崩溃了
运行的时候报错如下:
```
2017-07-31 09:24:48,789 jobs[daka] INFO: 登录状态: False
2017-07-31 09:24:48,789 jobs[daka] INFO: 进行登录...
Traceback (most recent call last):
  File "/Users/adam/Documents/JD-Coin/app/browser.py", line 75, in cookie_added
    self.cookies.set(cookie.key, cookie)
  File "/Users/adam/.pyenv/versions/3.6.2/lib/python3.6/site-packages/requests/cookies.py", line 213, in set
    c = morsel_to_cookie(value)
  File "/Users/adam/.pyenv/versions/3.6.2/lib/python3.6/site-packages/requests/cookies.py", line 484, in morsel_to_cookie
    time.strptime(morsel['expires'], time_template)
  File "/Users/adam/.pyenv/versions/3.6.2/lib/python3.6/_strptime.py", line 559, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/Users/adam/.pyenv/versions/3.6.2/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Wed, 30-Aug-2017 01:25:36 GMT' does not match format '%a, %d-%b-%Y %H:%M:%S GMT'
[1]    37119 abort      python ~/Documents/JD-Coin/app/main.py
```

**Comment by AdamChrist** [comment]
我尝试一下在Python环境下调用,发现没有问题,不知道为什么哪里里面有错误
```python
>>> import time
>>> time.strptime('Wed, 30-Aug-2017 01:25:36 GMT', '%a, %d-%b-%Y %H:%M:%S GMT')
time.struct_time(tm_year=2017, tm_mon=8, tm_mday=30, tm_hour=1, tm_min=25, tm_sec=36, tm_wday=2, tm_yday=242, tm_isdst=-1)
```
不懂Python..实在找不到哪里出了问题.

**Comment by knva** [comment]
换成qqlib的方式吧..这个浏览器多少麻烦一些

**Comment by AdamChrist** [comment]
反复测试了一下.是因为 `%a, %d`无法匹配 `Wed,Aug `这种`本地简化名称`造成的.于是做了如下测试:
- 在命令行下进入python环境没有问题.
- 用`python xxx.py`有这个问题.
- 把mac的语言改成英文,以上两种操作都没有问题.

**Comment by CaoZ** [comment]
对，就是因为这个原因，和系统的语言地区设置（Locale）有关系，可以算是 [Requests](https://github.com/requests) 的一个小 bug 吧，当时间格式不是英文格式时 Request 解析 cookie 时间的 pattern 就不正确了。

昨天翻了一下 Requests 的 issues，发现一些相关的 issue: https://github.com/requests/requests/issues/1859,  https://github.com/requests/requests/pull/1860#issuecomment-33696284. 连作者自己都说：

> I'm not sure, to be honest. I'm wondering if there's a good way we can confirm our cookie-parsing code works in all locales.

看来确实还有点问题...

不过我还有点搞不清 Python 什么时候会应用这个区域设置，可能和启动方式有关，比如我在 [bpython](https://bpython-interpreter.org/) 中：
```python
>>> from datetime import datetime
>>> datetime.now().strftime('%A')
'星期二'
```

直接启动 Python 却是：
```python
>>> from datetime import datetime
>>> datetime.now().strftime('%A')
'Tuesday'
```

可能改一下启动方式或是加个参数/环境变量之类的就能用命令行来启动了...
