### ISSUE TITLE
“京东客户端签到领京豆”失败了

### ISSUE THREAD

**Issue by wby238** [CaoZ/JD-Coin#22]
试了好几次，都提示同样的错误：

```log
2017-08-09 00:00:00,000 root[main] ERROR: # 任务运行出错: JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
Traceback (most recent call last):
  File "app/main.py", line 23, in main
    job.run()
  File "G:\git\JD-Coin\app\job\daka.py", line 41, in run
    self.job_success = self.sign()
  File "G:\git\JD-Coin\app\job\bean_app.py", line 50, in sign
    as_json = r.json()
  File "C:\Program Files\Python36\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by CaoZ** [comment]
嗯嗯，我也注意到了，是因为京东的签到页面更新了，原来接口不能用了（昨天我签到时还能用），稍后我更新下~

相关问题：https://github.com/CaoZ/JD-Coin/issues/9

**Comment by wby238** [comment]
thx
