### ISSUE TITLE
Binding request timed out from 0.0.0.x:55839

### ISSUE THREAD

**Issue by eromoe** [CaoZ/JD-Coin#29]
OS：win7
python: 3.5.3

1. 没有小白卡，貌似打卡就会失败

```
js: A Parser-blocking, cross-origin script, https://h5.360buyimg.com/ws_js/gatherInfo.js, is invoked
 via document.write. This may be blocked by the browser if the device has poor network connectivity.
 See https://www.chromestatus.com/feature/5718547946799104 for more details.
js: A Parser-blocking, cross-origin script, https://h5.360buyimg.com/ws_js/gatherInfo.js, is invoked
 via document.write. This may be blocked by the browser if the device has poor network connectivity.
 See https://www.chromestatus.com/feature/5718547946799104 for more details.
js: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects t
o the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
A Parser-blocking, cross-origin script, https://h5.360buyimg.com/ws_js/gatherInfo.js, is invoked via
 document.write. This may be blocked by the browser if the device has poor network connectivity. See
 https://www.chromestatus.com/feature/5718547946799104 for more details.
A Parser-blocking, cross-origin script, https://h5.360buyimg.com/ws_js/gatherInfo.js, is invoked via
 document.write. This may be blocked by the browser if the device has poor network connectivity. See
 https://www.chromestatus.com/feature/5718547946799104 for more details.
[1776:11636:0920/191003.239:ERROR:stunport.cc(89)] Binding request timed out from 0.0.0.x:52287 (any
)
```

2.  京东会员页签到领京豆 , 又一次弹出浏览器，这次登录要验证码，登录后出现
```
2017-09-20 19:13:03,566 jobs[daka] INFO: 登录状态: False
2017-09-20 19:13:03,566 jobs[daka] INFO: 进行登录...
[16024:5736:0920/191323.145:ERROR:stunport.cc(89)] Binding request timed out from 0.0.0.x:55839 (any
)

```
会卡在这里，强退浏览器才能终止

3.  强退2次后貌似就不会弹浏览器窗口了，出现下面这种错误

```
2017-09-20 19:18:23,251 jobs[bean] INFO: 今日已签到: False; 现在有 6639 个京豆.
2017-09-20 19:18:23,572 root[main] ERROR: # 任务运行出错: Exception('token 未找到.',)
Traceback (most recent call last):
  File "main.py", line 23, in main
    job.run()
  File "E:\Workspace\tools_github\JD-Coin\app\job\daka.py", line 43, in run
    self.job_success = self.sign()
  File "E:\Workspace\tools_github\JD-Coin\app\job\bean.py", line 34, in sign
    token = self._get_token()
  File "E:\Workspace\tools_github\JD-Coin\app\job\bean.py", line 57, in _get_token
    raise Exception('token 未找到.')
Exception: token 未找到.
2017-09-20 19:18:23,575 jobs[daka] INFO: Job Start: 京东金融签到领京豆
2017-09-20 19:18:23,883 jobs[daka] INFO: 登录状态: True
2017-09-20 19:18:23,977 root[main] ERROR: # 任务运行出错: KeyError('isSign',)
Traceback (most recent call last):
  File "main.py", line 23, in main
    job.run()
  File "E:\Workspace\tools_github\JD-Coin\app\job\daka.py", line 40, in run
    if self.is_signed():
  File "E:\Workspace\tools_github\JD-Coin\app\job\bean_jr.py", line 18, in is_signed
    signed = data['isSign']
KeyError: 'isSign'
=================================
= 任务数: 5; 失败数: 2
= 失败的任务: ['京东会员页签到领京豆', '京东金融签到领京豆']
=================================
```

PS: 我以前搞得京东领豆失效了很久了，一直懒得弄，今天闲来搜搜， 结果就看到这个项目，果断点赞

PS2: 话说为啥要用QT内置的浏览器，记得bug不少， selenium 不是更好？

**Comment by CaoZ** [comment]
感谢点赞~

1. 其实那是 Qt WebEngine (Chromium) 的一些输出, 也不能算报错... 暂时还不知道怎么屏蔽那些输出...

小白卡打卡可以[设置为跳过](https://github.com/CaoZ/JD-Coin#%E6%88%91%E6%B2%A1%E6%9C%89%E5%B0%8F%E7%99%BD%E5%8D%A1%E6%88%91%E6%83%B3%E8%B7%B3%E8%BF%87%E6%9F%90%E4%BA%9B%E4%BB%BB%E5%8A%A1), 不过在前两天(19号)[京东刚把这个活动关闭了](http://www.flyertea.com/thread-1757450-1-1.html), 以后应该会去掉这个功能.

2. 不是卡住了, 是需要手动关掉浏览器才能继续, [说明里](https://github.com/CaoZ/JD-Coin#%E8%AF%B4%E6%98%8E)有写:

 > 借助内置浏览器登录。本方式中使用 PyQt5 的 WebEngine 构建了个简易浏览器，在其中登录京东即可。
 > 
 > 登录后关掉浏览器窗口，程序会获取到 cookie，然后就可以继续签到了~

3. 这两个失败是因为京东最近更改了返回的结构, 由于国事繁忙我还没来得及改(😅)... 但是有用户已提了 [pull request](https://github.com/CaoZ/JD-Coin/pulls), 你可以先对照着自己改下, 近期我会改一下~~

4. 使用 Qt WebEngine 的主要目的是进行登录, 然后获得 cookes, 对 Selenium 不是很了解, 不知道能不能做到这点...

**Comment by eromoe** [comment]
了解~ 辛苦了啊

对于Selenium， 爬虫经常会用，就是调用本地浏览器进行操作，可以用ff，chrome 或者 phantomjs 等。不过要求客户机安装这些东西就是了，从一键安装的角度来说应该是不如 qt  方便。
