### ISSUE TITLE
没有图形界面怎么登录账号呢?....

### ISSUE THREAD

**Issue by Sir-H** [CaoZ/JD-Coin#36]
安装依赖后,添加josn,报错
2017-11-30 16:52:21,004 root[config] INFO: 使用配置文件 "config.json".
Traceback (most recent call last):
  File "./main.py", line 11, in <module>
    from job import jobs_all
  File "/root/JD-Coin/app/job/__init__.py", line 6, in <module>
    from .bean import Bean
  File "/root/JD-Coin/app/job/bean.py", line 4, in <module>
    from .daka import Daka
  File "/root/JD-Coin/app/job/daka.py", line 5, in <module>
    import browser
  File "/root/JD-Coin/app/browser.py", line 9, in <module>
    from PyQt5.QtGui import QIcon
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by CaoZ** [comment]
你好，你说的没图形界面是指登录窗口没出现呢还是压根没有图形界面环境呢？没图形界面暂时是不能登录的哦~

**Comment by Sir-H** [comment]
.没有图形界面环境的,能否二维码登录,然后获取cookie

**Comment by CaoZ** [comment]
没有图形环境的话, 二维码图像也不好显示吧... 不过理论上是可以的, 只是可能工作量会有点大... -_-||

**Comment by Sir-H** [comment]
...我安装图形界面吧,可以在tty下显示图片的...

**Comment by CaoZ** [comment]
嗯嗯, 那样 Qt 应该也能运行了吧...

**Comment by dawntonight** [comment]
@Sir-H 你是如何解决的？我在linux下也遇到这个问题了
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
