### ISSUE TITLE
京东会员签到突然出错

### ISSUE THREAD

**Issue by mpco** [CaoZ/JD-Coin#57]
非常感谢作者，一直很好用。

原本运行正常。今天突然出现问题。
输出如下：

```
INFO: Job Start: 京东会员页签到领京豆
2018-06-23 15:11:16,153 jobs[daka] INFO: 登录状态: True
2018-06-23 15:11:16,557 jobs[bean] INFO: 今日已签到: False; 现在有 750 个京豆.
2018-06-23 15:11:17,052 root[main] ERROR: # 任务运行出错: JSONDecodeError('Expecting value: line 2 column 1 (char 1)',)
Traceback (most recent call last):
  File "app/main.py", line 23, in main
    job.run()
  File "/Users/Charles/GitProjects/JD-Coin/app/job/daka.py", line 43, in run
    self.job_success = self.sign()
  File "/Users/Charles/GitProjects/JD-Coin/app/job/bean.py", line 40, in sign
    response = self.session.get(self.sign_url, params=payload).json()
  File "/Users/Charles/.local/share/virtualenvs/JD-Coin-u1aYOaCt/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

请问是什么问题呢？

**Comment by Cheshirem** [comment]
我的也是这种情况，我想可能是京东那边返回的数据格式改变了，或者是签到链接有变化。

**Comment by arsenalpoll** [comment]
@Cheshirem  应该是连接有变化，导致签到失败。

**Comment by CaoZ** [comment]
感谢提醒~ 问题已修复。原因是京东会员页签到方式调整了。
