### ISSUE TITLE
登陆报错  win10   python3

### ISSUE THREAD

**Issue by jiahao0321** [CaoZ/JD-Coin#64]
D:\python_test\JD-Coin-browser\JD-Coin-browser>python app/main.py
2018-07-24 10:21:57,170 root[config] INFO: 使用配置文件 "config.json".
2018-07-24 10:21:57,171 root[config] WARNING: 配置文件不存在, 使用默认配置文件 "config.default.json".
2018-07-24 10:21:57,173 root[config] INFO: 用户名/密码未找到, 自动登录功能将不可用.
Traceback (most recent call last):
  File "app/main.py", line 10, in <module>
    from job import jobs_all
  File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\job\__init__.py", line 6, in <module>
    from .bean import Bean
  File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\job\bean.py", line 4, in <module>
    from .daka import Daka
  File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\job\daka.py", line 5, in <module>
    import browser
  File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\browser.py", line 15, in <module>
    from PyQt5.uic.widgetplugins.qtwebenginewidgets import QWebEngineView
  File "D:\python35\lib\site-packages\PyQt5\uic\widgetplugins\qtwebenginewidgets.py", line 25, in <module>
    pluginType = MODULE
NameError: name 'MODULE' is not defined

D:\python_test\JD-Coin-browser\JD-Coin-browser>

**Comment by CaoZ** [comment]
你好，这个需要 Python 3.6 或以上，看看是不是这个原因呢？

**Comment by jiahao0321** [comment]
我这个就是3.6.5的 版本应该没问题~  方便加一下您的Q吗？

**Comment by CaoZ** [comment]
你好，重新检出代码来试下？我看 issue 里的代码好像不是我项目中的...
> File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\browser.py", line 15, in 
from PyQt5.uic.widgetplugins.qtwebenginewidgets import QWebEngineView
File "D:\python35\lib\site-packages\PyQt5\uic\widgetplugins\qtwebenginewidgets.py", line 25, in

**Comment by jiahao0321** [comment]
不知道为什么就一直报这个错误~ 找不到PYQT5的模块~  可是我已经pip 安装了官网的PYQT5了啊。。奇怪~ 郁闷死了。。  方便加一下我QQ 调试一下吗~  38714137


D:\python_test\JD-Coin-browser\JD-Coin-browser\app>main.py

D:\python_test\JD-Coin-browser\JD-Coin-browser\app>python main.py
2018-08-22 15:41:56,046 root[config] INFO: 使用配置文件 "config.json".
2018-08-22 15:41:56,068 root[config] WARNING: 配置文件不存在, 使用默认配置文件 "config.default.json".
2018-08-22 15:41:56,069 root[config] INFO: 用户名/密码未找到, 自动登录功能将不可用.
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from job import jobs_all
  File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\job\__init__.py", line 6, in <module>
    from .bean import Bean
  File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\job\bean.py", line 4, in <module>
    from .daka import Daka
  File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\job\daka.py", line 5, in <module>
    import browser
  File "D:\python_test\JD-Coin-browser\JD-Coin-browser\app\browser.py", line 11, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

D:\python_test\JD-Coin-browser\JD-Coin-browser\app>

**Comment by CaoZ** [comment]
感觉是 PyQt5 没有装对，你在目录下执行 pip list 能看到 PyQt5 吗？如果不能的话用 pip install PyQt5 装下再试试~

![untitled](https://user-images.githubusercontent.com/1962293/44455864-b11ee380-a631-11e8-9f05-dfe09ab44a16.png)

**Comment by jiahao0321** [comment]
谢谢大佬了！  应该是python版本和pyqt5 有问题  现在用python3.5   和 pyqt5的exe 安装文件 就可以了!  另外一定要主意python 32 还是64位   pyqt5一定要和python是一致的~   最后谢谢大佬！！！

**Comment by CaoZ** [comment]
不客气哈~~
